import string


class TokenType():
    DIGITS = "0123456789"
    LPAREN = "LPAREN"
    RPAREN = "RPAREN"
    PLUS = "PLUS"
    MINUS = "MINUS"
    MUL = "MUL"
    DIV = "DIV"
    POW = "POW"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    ENDFILE = 'ENDFILE'

    IDENTIFIER = 'IDENTIFIER'
    KEYWORD = 'KEYWORD'
    EQUALS = 'EQUALS'
    LETTERS = string.ascii_letters
    LETTERS_DIGITS = LETTERS + DIGITS
    EQUALSEQUALS = 'EQUALSEQUALS'
    NOTEQUALS='NOTEQUALS'
    LESSTHAN = 'LESSTHAN'
    GREATERTHAN='GREATHERTHAN'
    LESSTHANEQUALS='LESSTHANEQUALS'
    GREATERTHANEQUALS ='GREATERTHANEQUALS'




    KEYWORDS = ['VAR', 'AND', 'NOT', 'OR']
